### ISSUE TITLE
Redundant column

### ISSUE THREAD

**Issue by werka-z** [TO-perelki/testowanie#18]
[TESTPLAN.md#4.2](https://github.com/TO-perelki/testowanie/blob/main/TESTPLAN.md#42-role-i-odpowiedzialno%C5%9Bci) Column 'Person' is redundant as it only contains one value.

**Comment by N3jm4n** [comment]
We understand that the 'Person' column may appear redundant since it currently contains only one value. However, we have decided to keep it to enhance clarity and emphasize that both contributors will be working collaboratively on all tasks.

**Comment by N3jm4n** [comment]
We understand that the 'Person' column may appear redundant since it currently contains only one value. However, we have decided to keep it to enhance clarity and emphasize that both contributors will be working collaboratively on all tasks.
